# Note the 'jdbc:' prefix and the change in format
# jdbc:postgresql://dpg-d72hik94tr6s73bfvtq0-a.oregon-postgres.render.com:5432/ecommerce_xtgd?sslmode=require
spring.datasource.url= ${DB_URL}
spring.datasource.username= ${DB_USERNAME}
spring.datasource.password= ${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true